# Unit 12 - Tales from the Crypto

---

## 1. Sentiment Analysis

Use the [newsapi](https://newsapi.org/) to pull the latest news articles for Bitcoin and Ethereum and create a DataFrame of sentiment scores for each coin.

Use descriptive statistics to answer the following questions:
1. Which coin had the highest mean positive score?
2. Which coin had the highest negative score?
3. Which coin had the highest positive score?

In [1]:
# Initial imports
import os
import pandas as pd
from dotenv import load_dotenv
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

%matplotlib inline

In [2]:
# Read your api key environment variable
api_key = os.getenv('news_api')

In [3]:
# Create a newsapi client
from newsapi import NewsApiClient
newsapi = NewsApiClient(api_key=api_key)

In [4]:
# Fetch the Bitcoin news articles
btc_headlines = newsapi.get_everything(
    q="bitcoin",
    language="en",
    sort_by="relevancy"
)

In [5]:
# Fetch the Ethereum news articles
eth_headlines = newsapi.get_everything(
    q="ethereum",
    language="en",
    sort_by="relevancy"
)

In [6]:
eth_headlines

{'status': 'ok',
 'totalResults': 2773,
 'articles': [{'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Lucas Matney',
   'title': 'Offchain Labs raises $120 million to hide Ethereum’s shortcomings with its Arbitrum product',
   'description': 'As the broader crypto world enjoys a late summer surge in enthusiasm, more and more blockchain developers who have taken the plunge are bumping into the blaring scaling issues faced by decentralized apps on the Ethereum blockchain. The popular network has see…',
   'url': 'http://techcrunch.com/2021/08/31/offchain-labs-raises-120-million-to-hide-ethereums-shortcomings-with-arbitrum-scaling-product/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2021/08/Image-from-iOS-5.jpg?w=533',
   'publishedAt': '2021-08-31T12:30:39Z',
   'content': 'As the broader crypto world enjoys a late summer surge in enthusiasm, more and more blockchain developers who have taken the plunge are bumping into the blaring scaling issues faced by decentralized … [+3414 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Sarah Perez',
   'title': 'PayPal expands the ability to buy, hold and sell cryptocurrency to the U.K.',
   'description': 'PayPal will now allow users outside the U.S. to buy, hold and sell cryptocurrency for the first time. The company announced today the launch of a new service that will allow customers in the U.K. to select between four types of cryptocurrencies — including Bi…',
   'url': 'http://techcrunch.com/2021/08/23/paypal-expands-the-ability-to-buy-hold-and-sell-cryptocurrency-to-the-u-k/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2020/11/GettyImages-887657568.jpg?w=600',
   'publishedAt': '2021-08-23T13:49:45Z',
   'content': 'PayPal will now allow users outside the U.S. to buy, hold and sell cryptocurrency for the first time. The company announced today the launch of a new service that will allow customers in the U.K. to … [+4420 chars]'},
  {'source': {'id': 'engadget', 'name': 'Engadget'},
   'author': 'Daniel Cooper',
   'title': 'PayPal brings cryptocurrency trading to the UK',
   'description': 'PayPal is bringing the ability to buy, hold and sell cryptocurrencies across to the other side of the pond, the better part of a year after it launched in the US. In a statement, the company said that UK-based users would be able to buy, hold and sell Bitcoin…',
   'url': 'https://www.engadget.com/paypal-cryptocurrency-uk-101407842.html',
   'urlToImage': 'https://s.yimg.com/os/creatr-uploaded-images/2021-08/bf2cff60-03f9-11ec-99cb-501a3ec6e7a8',
   'publishedAt': '2021-08-23T10:14:07Z',
   'content': 'PayPal is bringing the ability to buy, hold and sell cryptocurrencies across to the other side of the pond, the better part of a year after it launched in the US. In a statement, the company said tha… [+850 chars]'},
  {'source': {'id': 'engadget', 'name': 'Engadget'},
   'author': 'Igor Bonifacic',
   'title': 'Poly Network says it has recovered all $610 million it lost in cryptocurrency heist',
   'description': 'One of the most unusual cryptocurrency heists in recent memory has come to a close. On Monday, Poly Network, a decentralized finance platform that saw a hacker named “Mr. White Hat” exploit a vulnerability in its code to steal $610 million in Ethereum, Shiba …',
   'url': 'https://www.engadget.com/poly-network-161726337.html',
   'urlToImage': 'https://s.yimg.com/os/creatr-uploaded-images/2021-08/9e7b0e60-fbb1-11eb-93bf-1d759aacf88d',
   'publishedAt': '2021-08-23T16:17:26Z',
   'content': 'One of the most unusual cryptocurrency heists in recent memory has come to a close. On Monday, Poly Network, a decentralized finance platform that saw a hacker named Mr. White Hat exploit a vulnerabi… [+1513 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'skiderlin@businessinsider.com (Sophie Kiderlin)',
   'title': "Ethereum co-creator Vitalik Buterin will help shape the future of dogecoin after joining the token's foundation",
   'description': 'Buterin has previously said a collaboration between ethereum and dogecoin could be possible, and has been supportive of the cryptocurrency.',
   'url': 'https://markets.businessinsider.com/news/currencies/vitalik-buterin-dogecoin-foundation-elon-musk-cryptocurrency-crypto-2021-8',
   'urlToImage': 'https://images2.markets.businessinsider.com/609d2bd2070a690018af4fff?format=jpeg',
   'publishedAt': '2021-08-18T10:39:49Z',
   'content': 'Vitalik Buterin, founder of ethereum, during TechCrunch Disrupt London 2015.\r\nJohn Phillips/Getty Images for TechCrunch\r\nEthereum co-creator Vitalik Buterin has joined the dogecoin foundation, which … [+2408 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'ewu@insider.com (Ethan Wu)',
   'title': "Citi will reportedly start trading bitcoin futures, following Goldman Sachs's lead as client demand for crypto spikes",
   'description': 'Citi had previously offered clients access to ethereum products but backed away after the 2017 "crypto winter" price crash.',
   'url': 'https://markets.businessinsider.com/news/currencies/citigroup-bank-crypto-bitcoin-futures-ethereum-goldman-sachs-cme-derivatives-2021-08',
   'urlToImage': 'https://images2.markets.businessinsider.com/612527a8493203001845a945?format=jpeg',
   'publishedAt': '2021-08-24T17:38:52Z',
   'content': 'Justin Sullivan/Getty Images\r\nCitigroup is actively recruiting traders to begin working with bitcoin futures, according to a new CoinDesk report.\r\nThe report, citing two sources including one within … [+1597 chars]'},
  {'source': {'id': 'reuters', 'name': 'Reuters'},
   'author': 'Huw Jones',
   'title': 'Digital identifiers to help crypto market go mainstream - Reuters',
   'description': 'Tags for identifying bitcoin, ethereum and other crypto assets will be launched in September in the latest sign of how the fast growing, unregulated market is adopting the hallmarks of mainstream investing.',
   'url': 'https://www.reuters.com/business/digital-identifiers-help-crypto-market-go-mainstream-2021-08-25/',
   'urlToImage': 'https://www.reuters.com/resizer/mxc0SEye7PVnWOZMRG7teFnOXIo=/1200x628/smart/filters:quality(80)/cloudfront-us-east-2.images.arcpublishing.com/reuters/GUUTBGHZSVNHBN6QND4LZRNZCM.jpg',
   'publishedAt': '2021-08-25T10:13:00Z',
   'content': 'LONDON, Aug 25 (Reuters) - Tags for identifying bitcoin, ethereum and other crypto assets will be launched in September in the latest sign of how the fast growing, unregulated market is adopting the … [+2613 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'insider@insider.com (Carla Mozée)',
   'title': 'Solana spikes above $100 for the first time as interest from institutions drives the DeFi coin up by 217% in August',
   'description': "Solana's price has rocketed during a furious run higher in August. The altcoin is often regarded as a competitor to Ethereum.",
   'url': 'https://www.businessinsider.com/solana-price-today-cryptocurrency-altcoins-nft-ethereum-bitcoin-2021-8',
   'urlToImage': 'https://i.insider.com/612d24d49ef1e50018f8c630?width=1200&format=jpeg',
   'publishedAt': '2021-08-30T20:02:49Z',
   'content': "Solana's SOL token surged above $100 for the first time on Monday, with a recent mix of projects and interest from institutional investors propelling the altcoin up by more than 200% as August winds … [+1616 chars]"},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'insider@insider.com (Grace Broadbent)',
   'title': 'PayPal bets big on crypto payments future with international expansion',
   'description': 'PayPal is making its first international crypto expansion with new services for Bitcoin, Ethereum, Litecoin, and Bitcoin Cash in the UK.',
   'url': 'https://www.businessinsider.com/paypal-expands-cryptocurrency-services-into-uk-2021-8',
   'urlToImage': 'https://i.insider.com/60f16e5a016a320018836973?width=1200&format=jpeg',
   'publishedAt': '2021-08-24T13:51:00Z',
   'content': "PayPal\xa0launched its crypto services in the UKits first international crypto expansion, according to a press release.\r\nPayPal's total payment volume reached $311 billion in Q2 2021.\r\nInsider Intellige… [+2125 chars]"},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'hrobertson@businessinsider.com (Harry Robertson)',
   'title': 'More than $144 million of ether has been burned since major network upgrades hit ethereum last week',
   'description': 'Investors have so far responded well to the ethereum network changes, with ether rising sharply since the fee-burn mechanism came into force.',
   'url': 'https://www.businessinsider.com/ether-burn-ethereum-crypto-upgrade-eip1559-london-hard-fork-price-2021-8',
   'urlToImage': 'https://i.insider.com/61168176c040ad0018ce298e?width=1200&format=jpeg',
   'publishedAt': '2021-08-15T13:58:48Z',
   'content': 'More than $144 million worth of ether has been burned since an overhaul of the fee system on the ethereum network went live on August 5.\r\nAs of Sunday, over 45,799 ether had been burned, according to… [+2017 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'hrobertson@businessinsider.com (Harry Robertson)',
   'title': 'More than $144 million of ether has been burned since major network upgrades hit ethereum last week',
   'description': 'Investors have so far responded well to the ethereum network changes, with ether rising sharply since the fee-burn mechanism came into force.',
   'url': 'https://markets.businessinsider.com/news/stocks/ether-burn-ethereum-crypto-upgrade-eip1559-london-hard-fork-price-2021-8',
   'urlToImage': 'https://images2.markets.businessinsider.com/61168176c040ad0018ce298e?format=jpeg',
   'publishedAt': '2021-08-15T13:58:48Z',
   'content': 'The ethereum network runs the ether cryptocurrency, the second-biggest after bitcoin.\r\nDado Ruvic/Reuters\r\nMore than $144 million worth of ether has been burned since an overhaul of the fee system on… [+2126 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Kyle Russell',
   'title': 'The Loot project flips the script on NFTs',
   'description': 'Editor’s note: Kyle Russell is the founder of Playbyte, a startup building an app that lets people make games on their phones. Last Friday, Dom Hofmann tweeted the launch of\xa0Loot, one of his new projects looking at games and game creation through the lens of …',
   'url': 'http://techcrunch.com/2021/09/03/loot-games-the-crypto-world/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2021/09/Screen-Shot-2021-09-03-at-5.26.16-AM.png?w=764',
   'publishedAt': '2021-09-03T12:29:19Z',
   'content': 'Editor’s note:Kyle Russell is the founder of Playbyte, a startup building an app that lets people make games on their phones.\r\nLast Friday, Dom Hofmann tweeted the launch of\xa0Loot, one of his new proj… [+7658 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'snagarajan@businessinsider.com (Shalini Nagarajan)',
   'title': 'Crypto exchange FTX quickly starts charging users $500 to mint their own NFTs after being spammed with images of fish',
   'description': 'FTX launches an NFT marketplace that lets users mint and sell their own digital items, with cross-chain selling between ethereum and solana, only to find it swamped with submissions.',
   'url': 'https://markets.businessinsider.com/news/currencies/ftx-nft-marketplace-buy-sell-create-non-fungible-tokens-crypto-2021-9',
   'urlToImage': 'https://images2.markets.businessinsider.com/61360303eedea900193d3a5a?format=jpeg',
   'publishedAt': '2021-09-06T14:35:04Z',
   'content': 'Alexi Rosenfeld/Getty Images\r\nCrypto exchange FTX has started charging a $500 fee for people to mint their own non-fungible token on its newly launched native NFT marketplace, after being swamped wit… [+2973 chars]'},
  {'source': {'id': None, 'name': 'Entrepreneur'},
   'author': 'Mairem Del Río',
   'title': 'Solana, rival of Ethereum, is already the seventh most valuable cryptocurrency on the market, surpassed Dogecoin!',
   'description': 'Solana has grown 35% in capitalization in just 24 hours and more than 800% in less than two months. Now, it is the seventh most valuable cryptocurrency on the market above Dogecoin, but it has not surpassed its rival Ethereum.',
   'url': 'https://www.entrepreneur.com/article/384229',
   'urlToImage': 'https://assets.entrepreneur.com/content/3x2/2000/1631057048-Sep8Solanacriptomonedaaltcoin.jpg',
   'publishedAt': '2021-09-08T11:00:00Z',
   'content': "This Tuesday, the 'altcoin' Solana (SOL) became the seventh cryptocurrency with the highest market capitalization above Dogecoin , Elon Musk's favorite. This currency, rival of Ethereum , has grown m… [+4452 chars]"},
  {'source': {'id': 'reuters', 'name': 'Reuters'},
   'author': 'Reuters Staff',
   'title': 'Ether above $4,000 for first time since May 15 - Reuters.com',
   'description': 'Ether, the second-biggest cryptocurrency, on Friday passed $4,000 for the first time since May 15, with analysts citing frenzied demand for non-fungible tokens (NFTs) as a driver of recent momentum.',
   'url': 'https://www.reuters.com/article/crypto-currency-ethereum-idUSL1N2Q51B2',
   'urlToImage': 'https://s1.reutersmedia.net/resources_v2/images/rcom-default.png?w=800',
   'publishedAt': '2021-09-03T14:51:00Z',
   'content': 'By Reuters Staff\r\nNEW YORK, Sept 3 (Reuters) - Ether, the second-biggest cryptocurrency, on Friday passed $4,000 for the first time since May 15, with analysts citing frenzied demand for non-fungible… [+577 chars]'},
  {'source': {'id': None, 'name': 'Slashdot.org'},
   'author': 'EditorDavid',
   'title': "Ethereum's Cryptocurrency Will 'Jettison' Mining for Speedier Proof-of-Stake",
   'description': '"Ethereum is making big changes," writes Bloomberg. "Perhaps the most important is the jettisoning of the \'miners\' who track and validate transactions on the the world\'s most-used blockchain network.\n\nMiners are the heart of a system known as proof of work. I…',
   'url': 'https://news.slashdot.org/story/21/08/15/048212/ethereums-cryptocurrency-will-jettison-mining-for-speedier-proof-of-stake',
   'urlToImage': 'https://a.fsdn.com/sd/topics/money_64.png',
   'publishedAt': '2021-08-15T10:34:00Z',
   'content': 'Miners are the heart of a system known as proof of work. It was pioneered by Bitcoin and adopted by Ethereum, and has come under increasing criticism for its environmental impact: Bitcoin miners now … [+1457 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'egraffeo@businessinsider.com (Emily Graffeo)',
   'title': 'VanEck files for an Ethereum futures ETF as crypto fund applications pile up at the SEC',
   'description': "VanEck's fund will not invest directly in ether, but invest in ether futures contracts and other pooled invested vehicles that provide exposure to the coin.",
   'url': 'https://markets.businessinsider.com/news/currencies/ethereum-futures-etf-vaneck-gary-gensler-ether-sec-approval-bitcoin-2021-8',
   'urlToImage': 'https://images2.markets.businessinsider.com/611e5e6c34808700196811cd?format=jpeg',
   'publishedAt': '2021-08-19T14:18:09Z',
   'content': 'Jack Taylor/Getty Images\r\nInvestment firm VanEck filed for an Ethereum futures-based exchange traded fund with the US Securities and Exchange Commission on Wednesday.\r\nAccording to the filing, the Et… [+961 chars]'},
  {'source': {'id': 'reuters', 'name': 'Reuters'},
   'author': 'Chuck Mikolajczak',
   'title': 'FOREX-Dollar softens after ADP; euro hits one-month high - Reuters.com',
   'description': '(New throughout, updates prices, market activity and comments, adds bitcoin, ethereum) * Graphic: World FX rates https://tmsnrt.rs/2RBWI5E By Chuck Mikolajczak NEW YORK, Sept 1 (Reuters) - The dollar fell against a basket of major currencies on Wednesday afte…',
   'url': 'https://www.reuters.com/article/global-forex-idUSL1N2Q327M',
   'urlToImage': 'https://s1.reutersmedia.net/resources_v2/images/rcom-default.png?w=800',
   'publishedAt': '2021-09-01T19:29:00Z',
   'content': '(New throughout, updates prices, market activity and comments, adds bitcoin, ethereum)\r\n * Graphic: World FX rates tmsnrt.rs/2RBWI5E\r\nBy Chuck Mikolajczak\r\n NEW YORK, Sept 1 (Reuters) - The dollar fe… [+3952 chars]'},
  {'source': {'id': 'engadget', 'name': 'Engadget'},
   'author': 'Mat Smith',
   'title': 'The Morning After: Crypto heist hacker returns all $610 million they stole',
   'description': 'It’s the weirdest cryptocurrency heist so far. On Monday, Poly Network, a cryptocurrency finance platform, was hacked by “Mr. White Hat” who exploited a vulnerability in its code to steal $610 million in Ethereum, Shiba Inu and other cryptocurrencies. The com…',
   'url': 'https://www.engadget.com/the-morning-after-crypto-heist-hacker-returns-all-610-million-they-stole-111630131.html',
   'urlToImage': 'https://s.yimg.com/os/creatr-uploaded-images/2021-08/5a314870-faa1-11eb-bfff-4f3c041dd826',
   'publishedAt': '2021-08-24T11:16:30Z',
   'content': 'Its the weirdest cryptocurrency heist so far. On Monday, Poly Network, a cryptocurrency finance platform, was hacked by Mr. White Hat who exploited a vulnerability in its code to steal $610 million i… [+6649 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Taylor Hatmaker',
   'title': 'CryptoPunks creator inks representation deal with major Hollywood talent agency',
   'description': 'One of Hollywood’s biggest talent agencies is getting into the NFT game. Larva Labs, the creator of CryptoPunks, just signed with United Talent Agency (UTA) in a representation deal that will bring one of the earliest and most iconic NFT projects into the ent…',
   'url': 'http://techcrunch.com/2021/08/31/larva-labs-cryptopunks-uta-meebits/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2021/08/cryptopunks-lucas.jpg?w=640',
   'publishedAt': '2021-08-31T19:52:29Z',
   'content': 'One of Hollywood’s biggest talent agencies is getting into the NFT game.\r\nLarva Labs, the creator of CryptoPunks, just signed with United Talent Agency (UTA) in a representation deal that will bring … [+2391 chars]'}]}

In [7]:
# Create the Bitcoin sentiment scores DataFrame
sentiments = []

for articles in btc_headlines["articles"]:
    try:
        text = articles["content"]
        results = analyzer.polarity_scores(text)
        compound = results["compound"]
        pos = results["pos"]
        neu = results["neu"]
        neg = results["neg"]

        sentiments.append({
            "text": text,
            "Compound": compound,
            "Positive": pos,
            "Negative": neg,
            "Neutral": neu,
        })
    except AttributeError:
        pass
    
btc  = pd.DataFrame(sentiments)
btc.head(20)

,text,Compound,Positive,Negative,Neutral
0,PayPal will now allow users outside the U.S. t...,0.4215,0.098,0.000,0.902
1,A recently-installed Bitcoin ATM.\r\n\n \n\n A...,0.1779,0.052,0.000,0.948
2,The government of El Salvador purchased at lea...,0.1280,0.046,0.000,0.954
3,Retailers are increasingly accepting cryptocur...,0.6187,0.153,0.000,0.847
4,"PayPal is bringing the ability to buy, hold an...",0.6908,0.161,0.000,0.839
5,By Joe TidyCyber reporter \r\nTaxi driver Chri...,-0.2960,0.053,0.114,0.833
6,New York (CNN Business)It's a volatile day for...,0.2023,0.074,0.054,0.872
7,"8. Were just days into September, and its time...",0.0000,0.000,0.000,1.000
8,A representation of cryptocurrency Bitcoin is ...,0.0000,0.000,0.000,1.000
9,"PayPal is to allow users in the UK to buy, hol...",0.4215,0.095,0.000,0.905
10,T-Mobile will offer two years of free identity...,0.5106,0.096,0.000,0.904
11,"Posted \r\nEl Zonte, El Salvador, home to 'Bit...",0.1280,0.049,0.000,0.951
12,Aug 27 (Reuters) - The first cryptocurrency AT...,0.0516,0.048,0.043,0.909
13,Aug 27 (Reuters) - The first cryptocurrency AT...,0.0516,0.048,0.043,0.909
14,"Posted \r\nEl Zonte, El Salvador, home to 'Bit...",0.1280,0.049,0.000,0.951
15,Twitter's latest beta update introduces suppor...,0.4019,0.083,0.000,0.917
16,Bitcoin plunged as much as 17 per cent to its ...,-0.5719,0.000,0.115,0.885
17,"Plunges as much as 17 per cent to US$43,050 \r...",-0.2023,0.038,0.060,0.902
18,T-Mobile is grappling with yet another reporte...,0.0000,0.000,0.000,1.000
19,PayPal launched its crypto services in the UKi...,0.2263,0.094,0.000,0.906

In [8]:
# Create the Ethereum sentiment scores DataFrame
sentiments = []

for articles in eth_headlines["articles"]:
    try:
        text = articles["content"]
        results = analyzer.polarity_scores(text)
        compound = results["compound"]
        pos = results["pos"]
        neu = results["neu"]
        neg = results["neg"]

        sentiments.append({
            "text": text,
            "Compound": compound,
            "Positive": pos,
            "Negative": neg,
            "Neutral": neu,
        })
    except AttributeError:
        pass
    
eth  = pd.DataFrame(sentiments)
eth.head(20)

,text,Compound,Positive,Negative,Neutral
0,As the broader crypto world enjoys a late summ...,0.7351,0.167,0.000,0.833
1,PayPal will now allow users outside the U.S. t...,0.4215,0.098,0.000,0.902
2,"PayPal is bringing the ability to buy, hold an...",0.6908,0.161,0.000,0.839
3,One of the most unusual cryptocurrency heists ...,-0.1027,0.000,0.043,0.957
4,"Vitalik Buterin, founder of ethereum, during T...",0.0000,0.000,0.000,1.000
5,Justin Sullivan/Getty Images\r\nCitigroup is a...,0.3182,0.076,0.000,0.924
6,"LONDON, Aug 25 (Reuters) - Tags for identifyin...",0.4404,0.136,0.000,0.864
7,Solana's SOL token surged above $100 for the f...,0.4588,0.081,0.000,0.919
8,PayPal launched its crypto services in the UKi...,0.2263,0.094,0.000,0.906
9,More than $144 million worth of ether has been...,0.2263,0.048,0.000,0.952
10,The ethereum network runs the ether cryptocurr...,0.2263,0.056,0.000,0.944
11,Editor’s note:Kyle Russell is the founder of P...,0.0000,0.000,0.000,1.000
12,Alexi Rosenfeld/Getty Images\r\nCrypto exchang...,0.1280,0.046,0.000,0.954
13,"This Tuesday, the 'altcoin' Solana (SOL) becam...",0.4588,0.094,0.000,0.906
14,"By Reuters Staff\r\nNEW YORK, Sept 3 (Reuters)...",-0.1280,0.000,0.048,0.952
15,Miners are the heart of a system known as proo...,-0.4404,0.000,0.079,0.921
16,Jack Taylor/Getty Images\r\nInvestment firm Va...,0.2960,0.068,0.000,0.932
17,"(New throughout, updates prices, market activi...",0.0000,0.000,0.000,1.000
18,Its the weirdest cryptocurrency heist so far. ...,-0.8934,0.000,0.312,0.688
19,One of Hollywood’s biggest talent agencies is ...,0.8126,0.219,0.000,0.781

In [9]:
# Describe the Bitcoin Sentiment
btc.describe()

        Compound   Positive   Negative    Neutral
count  20.000000  20.000000  20.000000  20.000000
mean    0.154425   0.061850   0.021450   0.916700
std     0.307322   0.046084   0.037859   0.049952
min    -0.571900   0.000000   0.000000   0.833000
25%     0.000000   0.044000   0.000000   0.897750
50%     0.128000   0.050500   0.000000   0.907500
75%     0.406800   0.094250   0.043000   0.951000
max     0.690800   0.161000   0.115000   1.000000

In [10]:
# Describe the Ethereum Sentiment
eth.describe()

        Compound   Positive   Negative    Neutral
count  20.000000  20.000000  20.000000  20.000000
mean    0.193730   0.067200   0.024100   0.908700
std     0.403785   0.065592   0.071127   0.077148
min    -0.893400   0.000000   0.000000   0.688000
25%     0.000000   0.000000   0.000000   0.892500
50%     0.226300   0.062000   0.000000   0.922500
75%     0.445000   0.095000   0.000000   0.952500
max     0.812600   0.219000   0.312000   1.000000

### Questions:

Q: Which coin had the highest mean positive score?

A: Eth by only a small amount @ 0.067200

Q: Which coin had the highest compound score?

A: Eth @ 0.81260

Q. Which coin had the highest positive score?

A: Eth @ 0.219

---

## 2. Natural Language Processing
---
###   Tokenizer

In this section, you will use NLTK and Python to tokenize the text for each coin. Be sure to:
1. Lowercase each word.
2. Remove Punctuation.
3. Remove Stopwords.

In [11]:
#Install nltk module and wordlist in terminal

!pip install --user -U nltk

Requirement already satisfied: nltk in /Users/johnlardis/.local/lib/python3.7/site-packages (3.6.2)
Requirement already satisfied: joblib in /Users/johnlardis/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from nltk) (1.0.1)
Requirement already satisfied: click in /Users/johnlardis/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from nltk) (7.1.2)
Requirement already satisfied: regex in /Users/johnlardis/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from nltk) (2021.4.4)
Requirement already satisfied: tqdm in /Users/johnlardis/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from nltk) (4.59.0)
^C

In [12]:
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from string import punctuation
import re

In [13]:
# Instantiate the lemmatizer
wnl = WordNetLemmatizer()

# Create a list of stopwords
stop = stopwords.words('english')

# Expand the default stopwords list if necessary
stop.append("u")
stop.append("it'")
stop.append("'s")
stop.append("n't")
stop.append('…')
stop.append("\`")
stop.append('``')
stop.append('char')
stop.append("''")
stop = set(stop)

In [14]:
btc['text']

0     PayPal will now allow users outside the U.S. t...
1     A recently-installed Bitcoin ATM.\r\n\n \n\n A...
2     The government of El Salvador purchased at lea...
3     Retailers are increasingly accepting cryptocur...
4     PayPal is bringing the ability to buy, hold an...
5     By Joe TidyCyber reporter \r\nTaxi driver Chri...
6     New York (CNN Business)It's a volatile day for...
7     8. Were just days into September, and its time...
8     A representation of cryptocurrency Bitcoin is ...
9     PayPal is to allow users in the UK to buy, hol...
10    T-Mobile will offer two years of free identity...
11    Posted \r\nEl Zonte, El Salvador, home to 'Bit...
12    Aug 27 (Reuters) - The first cryptocurrency AT...
13    Aug 27 (Reuters) - The first cryptocurrency AT...
14    Posted \r\nEl Zonte, El Salvador, home to 'Bit...
15    Twitter's latest beta update introduces suppor...
16    Bitcoin plunged as much as 17 per cent to its ...
17    Plunges as much as 17 per cent to US$43,050 \r...
18    T-Mobile is grappling with yet another reporte...
19    PayPal launched its crypto services in the UKi...
Name: text, dtype: object

In [15]:
# Complete the tokenizer function

In [16]:
# Create a new tokens column for Bitcoin

In [17]:
# Create a new tokens column for Ethereum

---

### NGrams and Frequency Analysis

In this section you will look at the ngrams and word frequency for each coin. 

1. Use NLTK to produce the n-grams for N = 2. 
2. List the top 10 words for each coin.

In [18]:
from collections import Counter
from nltk import ngrams

In [19]:
# Generate the Bitcoin N-grams where N=2
N = 2
grams = ngrams(tokenizer(btc.text.str.cat()), N)
Counter(grams).most_common(20)

NameError: name 'tokenizer' is not defined

In [ ]:
# Generate the Ethereum N-grams where N=2
N = 2
grams = ngrams(tokenizer(eth.text.str.cat()), N)
Counter(grams).most_common(20)

In [ ]:
# Function token_count generates the top 10 words for a given coin
def token_count(tokens, N=3):
    """Returns the top N tokens from the frequency count"""
    return Counter(tokens).most_common(N)

In [ ]:
# Use token_count to get the top 10 words for Bitcoin

In [ ]:
# Use token_count to get the top 10 words for Ethereum

---

### Word Clouds

In this section, you will generate word clouds for each coin to summarize the news for each coin

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [20.0, 10.0]

In [ ]:
# Generate the function for word cloud
def wordcloud(text, title=""):
    df_cloud = WordCloud(width=500, colormap='RdYlBu').generate(text)
    plt.imshow(df_cloud)
    plt.axis("off")
    fontdict = {"fontsize": 48, "fontweight" : "bold"}
    plt.title(title, fontdict=fontdict)
    plt.show()

In [ ]:
# Generate the BTC word cloud calling the function 
 wordcloud(btc.text.str.cat(), title="Bitcoin Word Cloud")

In [ ]:
# Generate the Ethereum word cloud calling the function 
 wordcloud(eth.text.str.cat(), title="Ethereum Word Cloud)

---
## 3. Named Entity Recognition

In this section, you will build a named entity recognition model for both Bitcoin and Ethereum, then visualize the tags using SpaCy.

In [ ]:
import spacy
from spacy import displacy

In [ ]:
# Download the language model for SpaCy
# !python -m spacy download en_core_web_sm

In [ ]:
# Load the spaCy model
nlp = spacy.load('en_core_web_sm')

---
### Bitcoin NER

In [ ]:
# Concatenate all of the Bitcoin text together

In [ ]:
# Run the NER processor on all of the text


# Add a title to the document

In [ ]:
# Render the visualization

In [ ]:
# List all Entities

---

### Ethereum NER

In [ ]:
# Concatenate all of the Ethereum text together

In [ ]:
# Run the NER processor on all of the text


# Add a title to the document

In [ ]:
# Render the visualization

In [ ]:
# List all Entities

---